//
//  PHPickerConfiguration.swift
//  JobsByPhotosUI
//
//  Generated by ChatGPT (DSL rebuild)
//  Created by Jobs on 23/2/26.
//

import Photos
import PhotosUI

@available(iOS 14.0, macOS 13.0, *)
@available(watchOS, unavailable)
@available(tvOS, unavailable)
public extension PHPickerConfiguration {
    /// TODO
}

@available(iOS 17.0, macOS 14.0, *)
@available(watchOS, unavailable)
public extension PHPickerConfiguration.Update {
    /// TODO
}

@available(iOS 14.0, macOS 13.0, *)
@available(watchOS, unavailable)
@available(tvOS, unavailable)
public extension PHPickerConfiguration.AssetRepresentationMode {
    /// TODO
}

@available(iOS 15.0, macOS 13.0, *)
@available(watchOS, unavailable)
@available(tvOS, unavailable)
public extension PHPickerConfiguration.Selection {
    /// TODO
}
