//
//  PHPickerFilter.swift
//  JobsByPhotosUI
//
//  Generated by ChatGPT (DSL rebuild)
//  Created by Jobs on 23/2/26.
//

import PhotosUI
import Photos
// ================================== PHPickerFilter ==================================
@available(iOS 14.0, macOS 13.0, watchOS 9.0, *)
@available(tvOS, unavailable)
extension PHPickerFilter {
    /// TODO
}
