//
//  PHPickerResult.swift
//  JobsByPhotosUI
//
//  Generated by ChatGPT (DSL rebuild)
//  Created by Jobs on 23/2/26.
//

import PhotosUI
import UniformTypeIdentifiers

@available(iOS 14.0, *)
@available(watchOS, unavailable)
@available(tvOS, unavailable)
extension PHPickerResult {
    /// TODO
}
