//
//  PHPickerCapabilities.swift
//  JobsByPhotosUI
//
//  Generated by ChatGPT (DSL rebuild)
//  Created by Jobs on 23/2/26.
//

import PhotosUI

@available(iOS 17.0, *)
extension PHPickerCapabilities {
    /// TODO
}
