//  UIFont+HYNuoMiTuanW.swift
//  Generated by ChatGPT
//

#if os(OSX)
import AppKit
#elseif os(iOS) || os(tvOS)
import UIKit
#endif

extension UIFont {
    enum HYNuoMiTuanW {

        public static func Regular(_ size: CGFloat) -> UIFont {
            switch Bundle.lang() {
            case .vietnamese, .turkish:
                return UIFont.Roboto.Regular(size)
            case .thai:
                return UIFont.Mitr.Regular(size)
            case .arabic:
                return UIFont.SFArabic.Regular(size)
            default:
                return make("HYNuoMiTuanW", size, fallback: .regular)
            }
        }

        private static func make(_ name: String,
                                 _ size: CGFloat,
                                 fallback: UIFont.Weight) -> UIFont {
            UIFont(name: name, size: size) ?? .systemFont(ofSize: size, weight: fallback)
        }
    }
}
