graph TD
  swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"] --> os_unfair_lock_lock_____["os_unfair_lock_lock(...)"]
  swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"] --> os_unfair_lock_unlock_____["os_unfair_lock_unlock(...)"]
  swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"] --> block_____["block(...)"]
  swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"] --> thread_____["thread(...)"]
  swift_func_JobsTimer_requireMainRunLoopForNonGCD______JobsSwiftTimer_swift_81["swift:func:JobsTimer.requireMainRunLoopForNonGCD(...)@JobsSwiftTimer.swift:81"] --> RunLoop_main_____["RunLoop.main(...)"]
  swift_func_JobsTimer_requireMainRunLoopForNonGCD______JobsSwiftTimer_swift_81["swift:func:JobsTimer.requireMainRunLoopForNonGCD(...)@JobsSwiftTimer.swift:81"] --> main_____["main(...)"]
  swift_init_JobsTimer_init______JobsSwiftTimer_swift_88["swift:init:JobsTimer.init(...)@JobsSwiftTimer.swift:88"] --> swift_func_JobsTimer_requireMainRunLoopForNonGCD______JobsSwiftTimer_swift_81["swift:func:JobsTimer.requireMainRunLoopForNonGCD(...)@JobsSwiftTimer.swift:81"]
  swift_init_JobsTimer_init______JobsSwiftTimer_swift_88["swift:init:JobsTimer.init(...)@JobsSwiftTimer.swift:88"] --> swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"]
  swift_deinit_JobsTimer_deinit_JobsSwiftTimer_swift_105["swift:deinit:JobsTimer.deinit@JobsSwiftTimer.swift:105"] --> stop_____["stop(...)"]
  swift_deinit_JobsTimer_deinit_JobsSwiftTimer_swift_105["swift:deinit:JobsTimer.deinit@JobsSwiftTimer.swift:105"] --> swift_func_JobsTimer_teardownAppState______JobsSwiftTimer_swift_466["swift:func:JobsTimer.teardownAppState(...)@JobsSwiftTimer.swift:466"]
  swift_func_JobsTimer_start______JobsSwiftTimer_swift_112["swift:func:JobsTimer.start(...)@JobsSwiftTimer.swift:112"] --> swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"]
  swift_func_JobsTimer_start______JobsSwiftTimer_swift_112["swift:func:JobsTimer.start(...)@JobsSwiftTimer.swift:112"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_start______JobsSwiftTimer_swift_112["swift:func:JobsTimer.start(...)@JobsSwiftTimer.swift:112"] --> swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"]
  swift_func_JobsTimer_start______JobsSwiftTimer_swift_112["swift:func:JobsTimer.start(...)@JobsSwiftTimer.swift:112"] --> swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"]
  swift_func_JobsTimer_start______JobsSwiftTimer_swift_112["swift:func:JobsTimer.start(...)@JobsSwiftTimer.swift:112"] --> swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"]
  swift_func_JobsTimer_start______JobsSwiftTimer_swift_112["swift:func:JobsTimer.start(...)@JobsSwiftTimer.swift:112"] --> swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"]
  swift_func_JobsTimer_pause______JobsSwiftTimer_swift_142["swift:func:JobsTimer.pause(...)@JobsSwiftTimer.swift:142"] --> swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"]
  swift_func_JobsTimer_pause______JobsSwiftTimer_swift_142["swift:func:JobsTimer.pause(...)@JobsSwiftTimer.swift:142"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_pause______JobsSwiftTimer_swift_142["swift:func:JobsTimer.pause(...)@JobsSwiftTimer.swift:142"] --> swift_func_JobsTimer_pauseGCD______JobsSwiftTimer_swift_336["swift:func:JobsTimer.pauseGCD(...)@JobsSwiftTimer.swift:336"]
  swift_func_JobsTimer_pause______JobsSwiftTimer_swift_142["swift:func:JobsTimer.pause(...)@JobsSwiftTimer.swift:142"] --> invalidate_____["invalidate(...)"]
  swift_func_JobsTimer_pause______JobsSwiftTimer_swift_142["swift:func:JobsTimer.pause(...)@JobsSwiftTimer.swift:142"] --> CFRunLoopTimerInvalidate_____["CFRunLoopTimerInvalidate(...)"]
  swift_func_JobsTimer_resume______JobsSwiftTimer_swift_171["swift:func:JobsTimer.resume(...)@JobsSwiftTimer.swift:171"] --> swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"]
  swift_func_JobsTimer_resume______JobsSwiftTimer_swift_171["swift:func:JobsTimer.resume(...)@JobsSwiftTimer.swift:171"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_resume______JobsSwiftTimer_swift_171["swift:func:JobsTimer.resume(...)@JobsSwiftTimer.swift:171"] --> swift_func_JobsTimer_resumeGCD______JobsSwiftTimer_swift_345["swift:func:JobsTimer.resumeGCD(...)@JobsSwiftTimer.swift:345"]
  swift_func_JobsTimer_resume______JobsSwiftTimer_swift_171["swift:func:JobsTimer.resume(...)@JobsSwiftTimer.swift:171"] --> swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"]
  swift_func_JobsTimer_resume______JobsSwiftTimer_swift_171["swift:func:JobsTimer.resume(...)@JobsSwiftTimer.swift:171"] --> swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"]
  swift_func_JobsTimer_resume______JobsSwiftTimer_swift_171["swift:func:JobsTimer.resume(...)@JobsSwiftTimer.swift:171"] --> swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"]
  swift_func_JobsTimer_fireOnce______JobsSwiftTimer_swift_195["swift:func:JobsTimer.fireOnce(...)@JobsSwiftTimer.swift:195"] --> Thread_isMainThread_____["Thread.isMainThread(...)"]
  swift_func_JobsTimer_fireOnce______JobsSwiftTimer_swift_195["swift:func:JobsTimer.fireOnce(...)@JobsSwiftTimer.swift:195"] --> fireOnce_____["fireOnce(...)"]
  swift_func_JobsTimer_fireOnce______JobsSwiftTimer_swift_195["swift:func:JobsTimer.fireOnce(...)@JobsSwiftTimer.swift:195"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_fireOnce______JobsSwiftTimer_swift_195["swift:func:JobsTimer.fireOnce(...)@JobsSwiftTimer.swift:195"] --> swift_func_JobsTimer_stopInternal______JobsSwiftTimer_swift_249["swift:func:JobsTimer.stopInternal(...)@JobsSwiftTimer.swift:249"]
  swift_func_JobsTimer_fireOnce______JobsSwiftTimer_swift_195["swift:func:JobsTimer.fireOnce(...)@JobsSwiftTimer.swift:195"] --> finish_____["finish(...)"]
  swift_func_JobsTimer_stop______JobsSwiftTimer_swift_220["swift:func:JobsTimer.stop(...)@JobsSwiftTimer.swift:220"] --> swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"]
  swift_func_JobsTimer_stop______JobsSwiftTimer_swift_220["swift:func:JobsTimer.stop(...)@JobsSwiftTimer.swift:220"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_stop______JobsSwiftTimer_swift_220["swift:func:JobsTimer.stop(...)@JobsSwiftTimer.swift:220"] --> swift_func_JobsTimer_stopInternal______JobsSwiftTimer_swift_249["swift:func:JobsTimer.stopInternal(...)@JobsSwiftTimer.swift:249"]
  swift_func_JobsTimer_onTick______JobsSwiftTimer_swift_238["swift:func:JobsTimer.onTick(...)@JobsSwiftTimer.swift:238"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_onFinish______JobsSwiftTimer_swift_244["swift:func:JobsTimer.onFinish(...)@JobsSwiftTimer.swift:244"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_stopInternal______JobsSwiftTimer_swift_249["swift:func:JobsTimer.stopInternal(...)@JobsSwiftTimer.swift:249"] --> swift_func_JobsTimer_stopGCDSafely______JobsSwiftTimer_swift_353["swift:func:JobsTimer.stopGCDSafely(...)@JobsSwiftTimer.swift:353"]
  swift_func_JobsTimer_stopInternal______JobsSwiftTimer_swift_249["swift:func:JobsTimer.stopInternal(...)@JobsSwiftTimer.swift:249"] --> invalidate_____["invalidate(...)"]
  swift_func_JobsTimer_stopInternal______JobsSwiftTimer_swift_249["swift:func:JobsTimer.stopInternal(...)@JobsSwiftTimer.swift:249"] --> CFRunLoopTimerInvalidate_____["CFRunLoopTimerInvalidate(...)"]
  swift_func_JobsTimer_routeStopIfNeededFromCallback______JobsSwiftTimer_swift_267["swift:func:JobsTimer.routeStopIfNeededFromCallback(...)@JobsSwiftTimer.swift:267"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_routeStopIfNeededFromCallback______JobsSwiftTimer_swift_267["swift:func:JobsTimer.routeStopIfNeededFromCallback(...)@JobsSwiftTimer.swift:267"] --> swift_func_JobsTimer_stopInternal______JobsSwiftTimer_swift_249["swift:func:JobsTimer.stopInternal(...)@JobsSwiftTimer.swift:249"]
  swift_func_JobsTimer_routeStopIfNeededFromCallback______JobsSwiftTimer_swift_267["swift:func:JobsTimer.routeStopIfNeededFromCallback(...)@JobsSwiftTimer.swift:267"] --> Thread_isMainThread_____["Thread.isMainThread(...)"]
  swift_func_JobsTimer_routeStopIfNeededFromCallback______JobsSwiftTimer_swift_267["swift:func:JobsTimer.routeStopIfNeededFromCallback(...)@JobsSwiftTimer.swift:267"] --> stop_____["stop(...)"]
  swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"] --> swift_func_JobsTimer_DisplayLinkProxy_tick______JobsSwiftTimer_swift_398["swift:func:JobsTimer.DisplayLinkProxy.tick(...)@JobsSwiftTimer.swift:398"]
  swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"] --> snapshot_repeats_____["snapshot.repeats(...)"]
  swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"] --> swift_func_JobsTimer_routeStopIfNeededFromCallback______JobsSwiftTimer_swift_267["swift:func:JobsTimer.routeStopIfNeededFromCallback(...)@JobsSwiftTimer.swift:267"]
  swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"] --> snapshot_finish_____["snapshot.finish(...)"]
  swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"] --> finish_____["finish(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> swift_func_JobsTimer_stopGCDSafely______JobsSwiftTimer_swift_353["swift:func:JobsTimer.stopGCDSafely(...)@JobsSwiftTimer.swift:353"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> DispatchSource_makeTimerSource_____["DispatchSource.makeTimerSource(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> makeTimerSource_____["makeTimerSource(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> t_schedule_____["t.schedule(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> schedule_____["schedule(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> now_____["now(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> milliseconds_____["milliseconds(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> Int_____["Int(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> t_setEventHandler_____["t.setEventHandler(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> t_resume_____["t.resume(...)"]
  swift_func_JobsTimer_startGCD______JobsSwiftTimer_swift_318["swift:func:JobsTimer.startGCD(...)@JobsSwiftTimer.swift:318"] --> resume_____["resume(...)"]
  swift_func_JobsTimer_pauseGCD______JobsSwiftTimer_swift_336["swift:func:JobsTimer.pauseGCD(...)@JobsSwiftTimer.swift:336"] --> t_suspend_____["t.suspend(...)"]
  swift_func_JobsTimer_pauseGCD______JobsSwiftTimer_swift_336["swift:func:JobsTimer.pauseGCD(...)@JobsSwiftTimer.swift:336"] --> suspend_____["suspend(...)"]
  swift_func_JobsTimer_resumeGCD______JobsSwiftTimer_swift_345["swift:func:JobsTimer.resumeGCD(...)@JobsSwiftTimer.swift:345"] --> t_resume_____["t.resume(...)"]
  swift_func_JobsTimer_resumeGCD______JobsSwiftTimer_swift_345["swift:func:JobsTimer.resumeGCD(...)@JobsSwiftTimer.swift:345"] --> resume_____["resume(...)"]
  swift_func_JobsTimer_stopGCDSafely______JobsSwiftTimer_swift_353["swift:func:JobsTimer.stopGCDSafely(...)@JobsSwiftTimer.swift:353"] --> t_resume_____["t.resume(...)"]
  swift_func_JobsTimer_stopGCDSafely______JobsSwiftTimer_swift_353["swift:func:JobsTimer.stopGCDSafely(...)@JobsSwiftTimer.swift:353"] --> resume_____["resume(...)"]
  swift_func_JobsTimer_stopGCDSafely______JobsSwiftTimer_swift_353["swift:func:JobsTimer.stopGCDSafely(...)@JobsSwiftTimer.swift:353"] --> t_setEventHandler_____["t.setEventHandler(...)"]
  swift_func_JobsTimer_stopGCDSafely______JobsSwiftTimer_swift_353["swift:func:JobsTimer.stopGCDSafely(...)@JobsSwiftTimer.swift:353"] --> swift_func_JobsSwiftTimerCountdown_cancel______JobsSwiftTimerCountdown_swift_163["swift:func:JobsSwiftTimerCountdown.cancel(...)@JobsSwiftTimerCountdown.swift:163"]
  swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"] --> swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"]
  swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"] --> swift_func_JobsTimer_requireMainRunLoopForNonGCD______JobsSwiftTimer_swift_81["swift:func:JobsTimer.requireMainRunLoopForNonGCD(...)@JobsSwiftTimer.swift:81"]
  swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"] --> Timer_____["Timer(...)"]
  swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"] --> swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"]
  swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"] --> runLoop_add_____["runLoop.add(...)"]
  swift_func_JobsTimer_startFoundationTimer______JobsSwiftTimer_swift_368["swift:func:JobsTimer.startFoundationTimer(...)@JobsSwiftTimer.swift:368"] --> add_____["add(...)"]
  swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"] --> swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"]
  swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"] --> swift_func_JobsTimer_requireMainRunLoopForNonGCD______JobsSwiftTimer_swift_81["swift:func:JobsTimer.requireMainRunLoopForNonGCD(...)@JobsSwiftTimer.swift:81"]
  swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"] --> swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"]
  swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"] --> CADisplayLink_____["CADisplayLink(...)"]
  swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"] --> selector_____["selector(...)"]
  swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"] --> link_add_____["link.add(...)"]
  swift_func_JobsTimer_startDisplayLink______JobsSwiftTimer_swift_380["swift:func:JobsTimer.startDisplayLink(...)@JobsSwiftTimer.swift:380"] --> add_____["add(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> swift_func_JobsTimer_requireMainThreadForRunLoopAPI______JobsSwiftTimer_swift_73["swift:func:JobsTimer.requireMainThreadForRunLoopAPI(...)@JobsSwiftTimer.swift:73"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> swift_func_JobsTimer_requireMainRunLoopForNonGCD______JobsSwiftTimer_swift_81["swift:func:JobsTimer.requireMainRunLoopForNonGCD(...)@JobsSwiftTimer.swift:81"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> Unmanaged_passUnretained_____["Unmanaged.passUnretained(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> UnsafeMutableRawPointer_____["UnsafeMutableRawPointer(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> passUnretained_____["passUnretained(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> toOpaque_____["toOpaque(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> CFRunLoopTimerContext_____["CFRunLoopTimerContext(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> CFAbsoluteTimeGetCurrent_____["CFAbsoluteTimeGetCurrent(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> CFRunLoopTimerCreate_____["CFRunLoopTimerCreate(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> fromOpaque_____["fromOpaque(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> takeUnretainedValue_____["takeUnretainedValue(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> swift_func_JobsUnfairLock_jobs_withLock______JobsSwiftTimer_swift_22["swift:func:JobsUnfairLock.jobs_withLock(...)@JobsSwiftTimer.swift:22"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> swift_func_JobsTimer_fireTickIfValid______JobsSwiftTimer_swift_290["swift:func:JobsTimer.fireTickIfValid(...)@JobsSwiftTimer.swift:290"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> runLoop_getCFRunLoop_____["runLoop.getCFRunLoop(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> getCFRunLoop_____["getCFRunLoop(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> CFRunLoopMode_____["CFRunLoopMode(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> CFRunLoopAddTimer_____["CFRunLoopAddTimer(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> canImport_____["canImport(...)"]
  swift_func_JobsTimer_startRunLoopTimer______JobsSwiftTimer_swift_401["swift:func:JobsTimer.startRunLoopTimer(...)@JobsSwiftTimer.swift:401"] --> swift_func_JobsAppStateManager_syncWithCurrentAppStateIfNeeded______JobsSwiftTim["swift:func:JobsAppStateManager.syncWithCurrentAppStateIfNeeded(...)@JobsSwiftTimer.swift"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> canImport_____["canImport(...)"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> JobsAppStateManager_____["JobsAppStateManager(...)"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> self_pause_____["self.pause(...)"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> pause_____["pause(...)"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> self_resume_____["self.resume(...)"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> resume_____["resume(...)"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> self_stop_____["self.stop(...)"]
  swift_func_JobsTimer_setupAppStateIfNeeded______JobsSwiftTimer_swift_448["swift:func:JobsTimer.setupAppStateIfNeeded(...)@JobsSwiftTimer.swift:448"] --> stop_____["stop(...)"]
  swift_func_JobsTimer_teardownAppState______JobsSwiftTimer_swift_466["swift:func:JobsTimer.teardownAppState(...)@JobsSwiftTimer.swift:466"] --> canImport_____["canImport(...)"]
  swift_init_JobsAppStateManager_init______JobsSwiftTimer_swift_483["swift:init:JobsAppStateManager.init(...)@JobsSwiftTimer.swift:483"] --> Sendable_____["Sendable(...)"]
  swift_init_JobsAppStateManager_init______JobsSwiftTimer_swift_483["swift:init:JobsAppStateManager.init(...)@JobsSwiftTimer.swift:483"] --> register_____["register(...)"]
  swift_func_JobsAppStateManager_syncWithCurrentAppStateIfNeeded______JobsSwiftTim["swift:func:JobsAppStateManager.syncWithCurrentAppStateIfNeeded(...)@JobsSwiftTimer.swift"] --> canImport_____["canImport(...)"]
  swift_func_JobsAppStateManager_syncWithCurrentAppStateIfNeeded______JobsSwiftTim["swift:func:JobsAppStateManager.syncWithCurrentAppStateIfNeeded(...)@JobsSwiftTimer.swift"] --> action_____["action(...)"]
  swift_func_JobsAppStateManager_register______JobsSwiftTimer_swift_503["swift:func:JobsAppStateManager.register(...)@JobsSwiftTimer.swift:503"] --> canImport_____["canImport(...)"]
  swift_func_JobsAppStateManager_register______JobsSwiftTimer_swift_503["swift:func:JobsAppStateManager.register(...)@JobsSwiftTimer.swift:503"] --> default_addObserver_____["default.addObserver(...)"]
  swift_func_JobsAppStateManager_register______JobsSwiftTimer_swift_503["swift:func:JobsAppStateManager.register(...)@JobsSwiftTimer.swift:503"] --> addObserver_____["addObserver(...)"]
  swift_func_JobsAppStateManager_register______JobsSwiftTimer_swift_503["swift:func:JobsAppStateManager.register(...)@JobsSwiftTimer.swift:503"] --> selector_____["selector(...)"]
  swift_func_JobsAppStateManager_unregister______JobsSwiftTimer_swift_520["swift:func:JobsAppStateManager.unregister(...)@JobsSwiftTimer.swift:520"] --> canImport_____["canImport(...)"]
  swift_func_JobsAppStateManager_unregister______JobsSwiftTimer_swift_520["swift:func:JobsAppStateManager.unregister(...)@JobsSwiftTimer.swift:520"] --> default_removeObserver_____["default.removeObserver(...)"]
  swift_func_JobsAppStateManager_unregister______JobsSwiftTimer_swift_520["swift:func:JobsAppStateManager.unregister(...)@JobsSwiftTimer.swift:520"] --> removeObserver_____["removeObserver(...)"]
  swift_func_JobsAppStateManager_onDidEnterBackground______JobsSwiftTimer_swift_52["swift:func:JobsAppStateManager.onDidEnterBackground(...)@JobsSwiftTimer.swift:526"] --> action_____["action(...)"]
  swift_func_JobsAppStateManager_onWillEnterForeground______JobsSwiftTimer_swift_5["swift:func:JobsAppStateManager.onWillEnterForeground(...)@JobsSwiftTimer.swift:530"] --> action_____["action(...)"]
  swift_deinit_JobsSwiftTimerCountdown_deinit_JobsSwiftTimerCountdown_swift_12["swift:deinit:JobsSwiftTimerCountdown.deinit@JobsSwiftTimerCountdown.swift:12"] --> swift_func_JobsSwiftTimerCountdown_cancel______JobsSwiftTimerCountdown_swift_163["swift:func:JobsSwiftTimerCountdown.cancel(...)@JobsSwiftTimerCountdown.swift:163"]
  swift_init_JobsSwiftTimerCountdown_init______JobsSwiftTimerCountdown_swift_98["swift:init:JobsSwiftTimerCountdown.init(...)@JobsSwiftTimerCountdown.swift:98"] --> swift_struct_JobsSwiftTimerCountdown_Snapshot_JobsSwiftTimerCountdown_swift_21["swift:struct:JobsSwiftTimerCountdown.Snapshot@JobsSwiftTimerCountdown.swift:21"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> swift_func_JobsSwiftTimerCountdown_resetInternal______JobsSwiftTimerCountdown_sw["swift:func:JobsSwiftTimerCountdown.resetInternal(...)@JobsSwiftTimerCountdown.swift:176"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> Date_____["Date(...)"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> swift_init_JobsSwiftTimerConfig_init______JobsSwiftTimerConfig_swift_29["swift:init:JobsSwiftTimerConfig.init(...)@JobsSwiftTimerConfig.swift:29"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> swift_init_JobsTimer_init______JobsSwiftTimer_swift_88["swift:init:JobsTimer.init(...)@JobsSwiftTimer.swift:88"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> timeIntervalSince_____["timeIntervalSince(...)"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> swift_struct_JobsSwiftTimerCountdown_Snapshot_JobsSwiftTimerCountdown_swift_21["swift:struct:JobsSwiftTimerCountdown.Snapshot@JobsSwiftTimerCountdown.swift:21"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> snapshot_total_____["snapshot.total(...)"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> stop_____["stop(...)"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> t_start_____["t.start(...)"]
  swift_func_JobsSwiftTimerCountdown_start______JobsSwiftTimerCountdown_swift_113["swift:func:JobsSwiftTimerCountdown.start(...)@JobsSwiftTimerCountdown.swift:113"] --> start_____["start(...)"]
  swift_func_JobsSwiftTimerCountdown_cancel______JobsSwiftTimerCountdown_swift_163["swift:func:JobsSwiftTimerCountdown.cancel(...)@JobsSwiftTimerCountdown.swift:163"] --> stop_____["stop(...)"]
  swift_func_JobsSwiftTimerCountdown_reset______JobsSwiftTimerCountdown_swift_171["swift:func:JobsSwiftTimerCountdown.reset(...)@JobsSwiftTimerCountdown.swift:171"] --> swift_func_JobsSwiftTimerCountdown_cancel______JobsSwiftTimerCountdown_swift_163["swift:func:JobsSwiftTimerCountdown.cancel(...)@JobsSwiftTimerCountdown.swift:163"]
  swift_func_JobsSwiftTimerCountdown_reset______JobsSwiftTimerCountdown_swift_171["swift:func:JobsSwiftTimerCountdown.reset(...)@JobsSwiftTimerCountdown.swift:171"] --> swift_func_JobsSwiftTimerCountdown_resetInternal______JobsSwiftTimerCountdown_sw["swift:func:JobsSwiftTimerCountdown.resetInternal(...)@JobsSwiftTimerCountdown.swift:176"]
  swift_func_JobsSwiftTimerCountdown_resetInternal______JobsSwiftTimerCountdown_sw["swift:func:JobsSwiftTimerCountdown.resetInternal(...)@JobsSwiftTimerCountdown.swift:176"] --> swift_struct_JobsSwiftTimerCountdown_Snapshot_JobsSwiftTimerCountdown_swift_21["swift:struct:JobsSwiftTimerCountdown.Snapshot@JobsSwiftTimerCountdown.swift:21"]
