graph LR
  component_JobsTimer["JobsTimer"] -->|protocol_conformance| component_JobsSwiftTimerProtocol["JobsSwiftTimerProtocol"]
  component_JobsTimer_State["JobsTimer.State"] -->|nested_type| component_JobsTimer["JobsTimer"]
  component_JobsTimer["JobsTimer"] -->|property_type| component_JobsTimerKind["JobsTimerKind"]
  component_JobsTimer["JobsTimer"] -->|property_type| component_JobsSwiftTimerConfig["JobsSwiftTimerConfig"]
  component_JobsTimer["JobsTimer"] -->|property_initialization| component_JobsUnfairLock["JobsUnfairLock"]
  component_JobsTimer["JobsTimer"] -->|property_type| component_JobsAppStateManager["JobsAppStateManager"]
  component_JobsTimer_DisplayLinkProxy["JobsTimer.DisplayLinkProxy"] -->|nested_type| component_JobsTimer["JobsTimer"]
  component_JobsAppStateManager["JobsAppStateManager"] -->|property_type| component_JobsAppStateAction["JobsAppStateAction"]
  component_JobsSwiftTimerCountdown_Snapshot["JobsSwiftTimerCountdown.Snapshot"] -->|nested_type| component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"]
  component_JobsSwiftTimerCountdown_Snapshot_Mode["JobsSwiftTimerCountdown.Snapshot.Mode"] -->|nested_type| component_JobsSwiftTimerCountdown_Snapshot["JobsSwiftTimerCountdown.Snapshot"]
  component_JobsSwiftTimerCountdown_State["JobsSwiftTimerCountdown.State"] -->|nested_type| component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"]
  component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"] -->|property_type| component_JobsTimerKind["JobsTimerKind"]
  component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"] -->|property_type| component_JobsSwiftTimerProtocol["JobsSwiftTimerProtocol"]
  component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"] -->|property_initialization| component_JobsSwiftTimerConfig["JobsSwiftTimerConfig"]
  component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"] -->|property_initialization| component_JobsTimer["JobsTimer"]
  component_extension_JobsSwiftTimerCountdown["extension JobsSwiftTimerCountdown"] -->|property_initialization| component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"]
  component_JobsSwiftTimerManager["JobsSwiftTimerManager"] -->|property_type| component_JobsSwiftTimerProtocol["JobsSwiftTimerProtocol"]
  component_JobsSwiftTimerManager["JobsSwiftTimerManager"] -->|property_type| component_JobsTimerDedupPolicy["JobsTimerDedupPolicy"]
  component_JobsSwiftTimerManager["JobsSwiftTimerManager"] -->|property_initialization| component_JobsTimer["JobsTimer"]
  component_JobsTimer["JobsTimer"] -->|member_call| component_JobsUnfairLock["JobsUnfairLock"]
  component_JobsTimer["JobsTimer"] -->|member_call| component_JobsTimer_DisplayLinkProxy["JobsTimer.DisplayLinkProxy"]
  component_JobsTimer["JobsTimer"] -->|call| component_JobsTimer_DisplayLinkProxy["JobsTimer.DisplayLinkProxy"]
  component_JobsTimer["JobsTimer"] -->|member_call| component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"]
  component_JobsTimer["JobsTimer"] -->|call| component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"]
  component_JobsTimer["JobsTimer"] -->|call| component_JobsAppStateManager["JobsAppStateManager"]
  component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"] -->|initializer_call| component_JobsSwiftTimerCountdown_Snapshot["JobsSwiftTimerCountdown.Snapshot"]
  component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"] -->|initializer_call| component_JobsSwiftTimerConfig["JobsSwiftTimerConfig"]
  component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"] -->|initializer_call| component_JobsTimer["JobsTimer"]
  component_extension_JobsSwiftTimerCountdown["extension JobsSwiftTimerCountdown"] -->|initializer_call| component_JobsSwiftTimerCountdown["JobsSwiftTimerCountdown"]
  component_JobsSwiftTimerManager["JobsSwiftTimerManager"] -->|initializer_call| component_JobsTimer["JobsTimer"]
